apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sourcegraph
bases:
  - ../bases/deployments
  - ../bases/rbac-roles
  - ../bases/pvcs
patchesStrategicMerge:
  - prometheus/prometheus.ClusterRoleBinding.yaml
  - prometheus/prometheus.ConfigMap.yaml
  - cadvisor/cadvisor.ClusterRoleBinding.yaml
